[build]
    command = "npm run build"
    publish = "/build"
    environment = { REACT_APP_API_URL = "https://countdown-quiz-api.herokuapp.com/" }

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
