services:
    api:
        container_name: countdown_test_api
        environment:
            - PGUSER=quizz_team
            - PGHOST=db
            - PGPASSWORD=countdownpass
            - PGDATABASE=quizz_db_test
            - PGPORT=5432
            - NODE_ENV=test
        depends_on:
            - db
        tty: true

    db:
        container_name: countdown_test_db
        volumes:
            - 'test_db:/var/lib/postgresql/data'
        environment:
            - POSTGRES_DB=quizz_db_test
            - POSTGRES_PASSWORD=countdownpass

volumes:
    test_db:
